server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BookMyShow
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update

    show-sql: true

application:
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days